### ISSUE TITLE
What's the meaning of the last three images in the generated results?

### ISSUE THREAD

**Issue by lilycai2000** [UCSB-NLP-Chang/DiffSTE#11]
After running the generation code, the result looks like:
![0-five-grid](https://github.com/UCSB-NLP-Chang/DiffSTE/assets/135924469/3af247d7-701b-4f6c-a84d-99e4faf42b01)
What does the last three images mean and what's the difference? Thanks so much!

**Comment by thebestYezhang** [comment]
if means results with different random noise.

**Comment by lilycai2000** [comment]
> if means results with different random noise.

Are they the inferences from different training stages?

**Comment by thebestYezhang** [comment]
Nope. You can check it in the source code inpaint_trainer.py



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/13/2023 05:05 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [UCSB-NLP-Chang/DiffSTE] What's the meaning of the last three images in the generated results? (Issue #11) |

if means results with different random noise.

Are they the inferences from different training stages?

**Comment by Question406** [comment]
yes, the last three columns are images generated starting from three different noise by the same model.

**Comment by lilycai2000** [comment]
> yes, the last three columns are images generated starting from three different noise by the same model.

Thanks! Do you mean it did the inference three times separately?

**Comment by Question406** [comment]
kind of, these images are generated in a batch with different initial noise. it's the same as running inference to generate one image three times but faster than it

**Comment by lilycai2000** [comment]
thank you!
