### ISSUE TITLE
Command for resume training the model

### ISSUE THREAD

**Issue by lilycai2000** [UCSB-NLP-Chang/DiffSTE#13]
Thank you so much for your great research!

Regarding training on my own dataset, I was trying to resume training the model with the provided checkpoint. In that case, what command should be used? 

Thanks so much!

**Comment by Question406** [comment]
Hi, it should be something like:

`python train.py --resume BASE_CHECKPOINT_DIRECTORY`

**Comment by lilycai2000** [comment]
thanks so much!
