### ISSUE TITLE
update version in requirements.txt and README

### ISSUE THREAD

**Issue by yejinc00** [UCSB-NLP-Chang/DiffSTE#2]
I'm interested in scene text editing, so I read your "Improving Diffusion Models for Scene Text Editing with Dual Encoders". I think this is awesome research.

I tried generation by following the README, but I found two small problems below.
1. need to update `jax==0.4.7` in `requirements.txt`
2. need to change `--output_dir` to `--out_dir` in the README's generate code

thank you😊

**Comment by Question406** [comment]
Thank you for reminding us! We have updated the requirement and `generate.py`.

**Comment by Apostatee** [comment]
still "output_dir"  in the README's generate code
