### ISSUE TITLE
Cannot download finetuned VAE

### ISSUE THREAD

**Issue by alvaro-budria** [UCSB-NLP-Chang/DiffSTE#23]
Hi, I executed the commands under the Quick Start section in the README, and am running into an issue related to the finetuned VAE model.

It seems I don't have permissions to download the weights or they do not exist.

I get the following error messages:
```
HTTPError: 401 Client Error: Unauthorized for url: 
https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/caac1048f28756b68042add4670bec6f4ae314f8/vae/diffusion_pytorch_model.bin
```

```
RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66d80e3e-1048b5ca6a390d527254d5b4)

Repository Not Found for url: https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/caac1048f28756b68042add4670bec6f4ae314f8/vae/diffusion_pytorch_model.bin.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

```
OSError: runwayml/stable-diffusion-inpainting is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.
```

Is this behavior expected? Can you please indicate what I should do?

**Comment by alvaro-budria** [comment]
It seems that Runway took down the Stable Diffusion v1.5 from HuggingFace: https://www.aibase.com/news/11434.

**Comment by shkr** [comment]
I have the same issue. I am not sure which diffusion model to use.

**Comment by alvaro-budria** [comment]
Hi, I solved this issue by downloading the weights from a mirror that I found on [this reddit comment](https://www.reddit.com/r/StableDiffusion/comments/1f4epto/comment/lklkpcl/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).
