### ISSUE TITLE
outside the mask area is changed

### ISSUE THREAD

**Issue by Laidawang** [UCSB-NLP-Chang/DiffSTE#6]
![WechatIMG127](https://user-images.githubusercontent.com/85244566/234791590-5fd32a96-5159-4206-971e-762b06a9765e.png)
![下载 (1)](https://user-images.githubusercontent.com/85244566/234791603-99aedbed-9ea7-4639-93cf-75917b0ba8e8.png)
![mask](https://user-images.githubusercontent.com/85244566/234792615-00c6b314-246c-49dd-96a5-97a944b624ea.png)
You can see that compared with the original image, the unmasked areas have also changed. Is there any good way for me to avoid this? Thanks

**Comment by Question406** [comment]
Hi, one thing you could try is to apply an attention-mask to cross-attention, similar to another work in our group(https://github.com/UCSB-NLP-Chang/Diffusion-SpaceTime-Attn).
