### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets' when running generation

### ISSUE THREAD

**Issue by lilycai2000** [UCSB-NLP-Chang/DiffSTE#9]
Hi, when I was running 'python generate.py --ckpt_path ${model_path} --in_image examples/sample0.png --in_mask examples/mask0.png --text wizards --output_dir ${output_dir}', there was an error: 'ModuleNotFoundError: No module named 'datasets''.
I didn't see any dataset folder in this repo, any idea on how to solve this problem?

Thanks!

**Comment by Question406** [comment]
Hi, I think this module should be the `datasets` library from huggingface, https://huggingface.co/docs/datasets/index. I checked the requirements and find that it is included. Did you check if the environment is correctly installed?

**Comment by lilycai2000** [comment]
thanks it's solved!!
